#Character constants
CHAR__AT = '@'
CHAR__PIPE = '|'
CHAR__EMPTY = ''
CHAR__SPACE = ' '
CHAR__COMMA = ','
CHAR__PERIOD = '.'
CHAR__COLON = ':'
CHAR__HYPHEN = '-'
CHAR__ASTERIX = '*'
CHAR__NEWLINE = '\n'
CHAR__UNDSERSCORE = '_'
CHAR__EXCLAIMATION = '!'
CHAR__SINGLE_QUOTE = '\''
CHAR__DOUBLE_QUOTE = "\""
CHAR__FORWARD_SLASH = '/'
CHAR__BACKWARD_SLASH = '\\'
CHAR__OPENCURLYBRACKET = '{'
CHAR__CLOSECURLYBRACKET = '}'
CHAR__OPENSQUAREBRACKET = '['
CHAR__CLOSESQUAREBRACKET = ']'

#Number constants
NUMBER__INDEX_ZER0 = 0

#Date Time Constants
DATETIME_FORMAT__MON_DAY_YR_TIME = '%b %d %Y %H:%M:%S'

#File constants
FILE_OPERATION__READ = 'r'
FILE_OPERATION__WRITE = 'w'

#Format Constants
FORMAT_CHARSET = 'Charset'
FORMAT_CHARSET__UTF8 = 'UTF-8'

#File extension constants
FILE_EXTENSION__JSON = '.json'

#Configuration constants
CONFIGURATION__SETTINGS = 'Settings'

#Media Format constants
MEDIA = 'Media'
MEDIA_FILE_URI = 'MediaFileUri'
MEDIA_FILE_FORMAT = 'MediaFormat'
MEDIA_FILE_FORMAT__MP3 = 'mp3'
MEDIA_FILE_FORMAT__MP4 = 'mp4'

#Language Code constants
LANGUAGE_CODE = 'LanguageCode'
LANGUAGE_CODE__ENGLISH_US = 'en-US'
LANGUAGE_CODE__ENGLISH_UK = 'en-GB'
LANGUAGE_CODE__ENGLISH_AUS = 'en-AU'
LANGUAGE_CODE__ENGLISH_IND = 'en-IN'

#Event Constants
EVENT_METADATA__RECORDS = 'Records'
EVENT_METADATA__BODY = 'body'
EVENT_METADATA__NAME = 'name'
EVENT_METADATA__MESSAGE = 'Message'

#HTTP Constants
HTTP__PREFIX = 'http://'
HTTPS__PREFIX = 'https://'
HTTP_METADATA__BODY = 'body'
HTTP_METADATA__STATUS_CODE = 'statuscode'
HTTP_METADATA__STATUS_CODE_SUCCESS = 200
HTTP_METADATA__STATUS_CODE_INTERNAL_ERROR = 500
HTTP_METADATA__STATUS_CODE_BAD_REQUEST_ERROR = 400
HTTP_METADATA__STATUS_CODE_ACCESS_DENIED_ERROR = 401
HTTP_METADATA__STATUS_CODE_ACCESS_FORBIDDEN_ERROR = 403
HTTP_METADATA__STATUS_CODE_RESOURCE_NOT_FOUND_ERROR = 404

# ---------------- Unicorn-Gym Hackathon (UGH) constants --------------------

#Application constants
UGH_PC__APPLICATION_CODE = 'ugh_pca'
UGH_PC__APPLICATION_ID = '1db38593-e6d5-4657-8e09-dc71b8df3d58'
UGH_PC__APPLICATION_NAME = 'unicorn-gym-hackathon-presentation-creator-app'

#JSON Schema constants
UGH_PC_JSE__SLIDES = 'slides'
UGH_PC_JSE__TRANSCRIPT = 'transcript'
UGH_PC_JSE__SLIDENUMBER = 'slideNumber'
UGH_PC_JSE__SLIDEIMAGE = 'slideimage'
UGH_PC_JSE__SLIDEIMAGEPREFIX = 'slidePrefix'
UGH_PC_JSE__SLIDEIMAGEMIMETYPE = 'slideImageMimeType'

#DynamoDB Schema constants

# Table: user_jobs
UGH_PC_DDB_TABLENAME__USER_JOBS = 'user_jobs'
# Fields
UGH_PC_DDB_PK__USER_EMAIL_ID = "user_email_id"
UGH_PC_DDB_SK__USER_JOB_ID = "job_id"
UGH_PC_DDB_FLD__LAST_UPDATED = 'last_updated'
UGH_PC_DDB_FLD__OVERWRITE_NOTES = 'overwrite_notes'
UGH_PC_DDB_FLD__JOB_STATUS = 'job_status'
UGH_PC_DDB_FLD__JOB_ARTIFACTS = 'job_artifacts'

# Table: application_configuration
UGH_PC_DDB_TABLENAME__APP_CONFIG = 'app_config'
# Fields
UGH_PC_DDB_FLD__AC_APPLICATION_ID = 'application_id'
UGH_PC_DDB_FLD__AC_APPLICATION_CODE = 'application_code'
UGH_PC_DDB_FLD__AC_APPLICATION_NAME = 'application_name'
UGH_PC_DDB_FLD__AC_PRESENTATION_TEMPLATE_FILENAME = 'PresentationTemplateFilename'
UGH_PC_DDB_FLD__AC_TRANSCRIPTIONS_FILENAME = 'TranscriptionsFilename'	
UGH_PC_DDB_FLD__AC_SLIDE_TRANSCRIPTIONS_FILENAME = 'SlideTranscriptionsFilename'	
UGH_PC_DDB_FLD__AC_BUCKETNAME = 'BucketName'
UGH_PC_DDB_FLD__AC_JOB_PREFIX = 'JobPrefix'
UGH_PC_DDB_FLD__AC_SLIDES_PREFIX = 'SlidesPrefix'
UGH_PC_DDB_FLD__AC_BUCKET_PREFIX = 'BucketPrefix'
UGH_PC_DDB_FLD__AC_SLIDE_TRANSITIONS_FILENAME = 'SlideTransitionsFilename'
UGH_PC_DDB_FLD__AC_VIDEO_FILENAME = 'VideoFilename'
UGH_PC_DDB_FLD__AC_PRESENTATION_FILENAME = 'PresentationFileName'
UGH_PC_DDB_FLD__AC_TEMPLATES_PREFIX = 'TemplatesPrefix'
UGH_PC_DDB_FLD__AC_CREATE_PRESENTATION_QUEUENAME = 'CreatePresentationQueueName'
UGH_PC_DDB_FLD__AC_SEND_EMAIL_QUEUENAME = 'SendEmailQueueName'
UGH_PC_DDB_FLD__AC_PROCESS_VIDEO_QUEUENAME = 'ProcessVideoQueueName'
UGH_PC_DDB_FLD__AC_SEND_EMAIL_SOURCENAME = 'SendEmailSourceName'


#Job status updates
UGH_PC_DDB_FLDVALUE__STATUS_STARTED = 'Started: '
UGH_PC_DDB_FLDVALUE__STATUS_FAILED = 'Failed: '
UGH_PC_DDB_FLDVALUE__STATUS_COMPLETE = 'Completed: '
UGH_PC_DDB_FLDVALUE__STATUS_RETRY = 'Retry: '
UGH_PC_DDB_FLDVALUE__JOB_STATUS_STARTED = 'Job Started'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_FILES_UPLOAD_COMPLETE = 'Job Files Upload'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_PROCESSING_VIDEO = 'Processing Video'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_PROCESSING_AUDIO = 'Processing Audio'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_CREATING_NOTES = 'Creating Notes'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_CREATING_PRESENTATION = 'Creating Presentation'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_SENDING_EMAIL_NOTIFICATION = 'Sending Email Notification'
UGH_PC_DDB_FLDVALUE__JOB_STATUS_COMPLETED = 'Job Completed'